#!/bin/sh

echo "***************************************************************************"
echo "* The following commands are available.                                   *"
echo "* - ct6_tool.py                                                           *"
echo "* Configure and calibrate CT6 devices                                     *"
echo "* - ct6_db_store                                                          *"
echo "* Allow data from CT6 devices to be stored in a MYSQL databse.            *"
echo "* - ct6_dash                                                              *"
echo "* Display a dashboard to read and display the data in the database.       *"
echo "* - ct6_dash_mgr                                                          *"
echo "* Add/Remove users to the access list for the server if enabled in config *"
echo "***************************************************************************"
