#!/bin/bash

set -e

check_internet_connectivity()
{
echo "Checking Internet connection"
#8.8.8.8 is used as it's googles dns server which should be available on the internet
if ping -q -c 1 -W 1 8.8.8.8 >/dev/null; then
  echo "Connected to the Internet"
else
  echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
  echo "! This computer is not connected to the internet !"
  echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
  echo "Connect this computer to the Internet and then try again"
  exit 1
fi
}

if !(which python3) > /dev/null ; then
  echo "****************************************************************"
  echo "* Python3 is not installed is not installed on your computer   *"
  echo "****************************************************************"
  check_internet_connectivity
  echo "Run the following commands to install python3.9."
  echo "    sudo apt install build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev libsqlite3-dev wget curl"
  echo "    sudo apt install libssl-dev libffi-dev"
  echo "    cd /tmp"
  echo "    curl -O https://www.python.org/ftp/python/3.9.7/Python-3.9.7.tar.xz"
  echo "    tar -xf Python-3.9.7.tar.xz"
  echo "    cd Python-3.9.7"
  echo "    ./configure --enable-optimizations"
  echo "    sudo make altinstall"
  echo "When the above steps are complete try installing this package again"
  exit 1
fi

# We must ensure that pip3 and pipenv packages are insalled
# as the are required. Return 1 if pip3 or pipenv is not installed.
if !(which pip3) > /dev/null ; then
  echo "***********************************************************"
  echo "* pip3 is not installed is not installed on your computer *"
  echo "***********************************************************"
  check_internet_connectivity
  echo "Run the following command."
  echo "    sudo apt install python3-pip"
  exit 1
fi

if !(which pipenv) > /dev/null ; then
  echo "*************************************************************"
  echo "* pipenv is not installed is not installed on your computer *"
  echo "*************************************************************"
  check_internet_connectivity
  echo "Run the following command."
  echo "    sudo pip3 install pipenv"
  exit 1
fi
